// src/data.js
import picture from "./assets/picture.jpg"
export const products = [
  {
    id: 1,
    category: "pizza",
    name: "Freddy's Face Pizza",
    description: "Пицца в форме головы Фредди",
    image: picture, // загрузишь сам
    largeImage: "freddy_pizza_large.jpg",
    ingredients: ["Томатный соус", "Сыр моцарелла", "Колбаса", "Оливки"],
    weight: "500 г",
    price: 499,
  },
  {
    id: 2,
    category: "pizza",
    name: "Chica's Chicken Pizza",
    description: "Куриная пицца от Чики",
    image: "chica_pizza.jpg",
    largeImage: "chica_pizza_large.jpg",
    ingredients: ["Сливочный соус", "Курица", "Грибы", "Лук"],
    weight: "480 г",
    price: 479,
  },

  {
    id: 3,
    category: "snack",
    name: "Bonnie's Bites",
    description: "Хрустящие кусочки Бонни",
    image: "bonnie_snack.jpg",
    largeImage: "bonnie_snack_large.jpg",
    ingredients: ["Куриные наггетсы", "Специи", "Тесто"],
    weight: "200 г",
    price: 199,
  },
  {
    id: 4,
    category: "snack",
    name: "Fazbear's Fries",
    description: "Картофель фри от Фазбер",
    image: "fries.jpg",
    largeImage: "fries_large.jpg",
    ingredients: ["Картофель", "Соль", "Масло"],
    weight: "300 г",
    price: 149,
  },

  {
    id: 5,
    category: "salad",
    name: "Golden Salad",
    description: "Салат золотого цвета",
    image: "golden_salad.jpg",
    largeImage: "golden_salad_large.jpg",
    ingredients: ["Айсберг", "Огурцы", "Фасоль", "Соус"],
    weight: "250 г",
    price: 179,
  },
  {
    id: 6,
    category: "salad",
    name: "Nightmare Salad",
    description: "Чёрный салат с пикантным вкусом",
    image: "nightmare_salad.jpg",
    largeImage: "nightmare_salad_large.jpg",
    ingredients: ["Шпинат", "Оливки", "Соус чёрного перца"],
    weight: "220 г",
    price: 189,
  },

  {
    id: 7,
    category: "roll",
    name: "Springtrap Roll",
    description: "Роллы в виде пружины",
    image: "springtrap_roll.jpg",
    largeImage: "springtrap_roll_large.jpg",
    ingredients: ["Рис", "Сыр", "Сырокопченая колбаса"],
    weight: "300 г",
    price: 299,
  },
  {
    id: 8,
    category: "roll",
    name: "Marionette Roll",
    description: "Роллы с креветками",
    image: "marionette_roll.jpg",
    largeImage: "marionette_roll_large.jpg",
    ingredients: ["Креветки", "Авокадо", "Рис", "Нори"],
    weight: "280 г",
    price: 329,
  },

  {
    id: 9,
    category: "dessert",
    name: "Pizza Cupcake",
    description: "Капкейк в виде пиццы",
    image: "pizza_cupcake.jpg",
    largeImage: "pizza_cupcake_large.jpg",
    ingredients: ["Бисквит", "Крем-сыр", "Шоколад"],
    weight: "100 г",
    price: 99,
  },
  {
    id: 10,
    category: "dessert",
    name: "Cupcake Freddy",
    description: "Капкейк в виде Фредди",
    image: "freddy_cupcake.jpg",
    largeImage: "freddy_cupcake_large.jpg",
    ingredients: ["Ванильный бисквит", "Крем", "Шоколадные глаза"],
    weight: "90 г",
    price: 109,
  },

  {
    id: 11,
    category: "drink",
    name: "Purple Drink",
    description: "Фиолетовый напиток",
    image: "purple_drink.jpg",
    largeImage: "purple_drink_large.jpg",
    ingredients: ["Сироп", "Лимонад", "Лёд"],
    volume: "500 мл",
    price: 89,
  },
  {
    id: 12,
    category: "drink",
    name: "Glitch Drink",
    description: "Напиток с эффектом Glitch",
    image: "glitch_drink.jpg",
    largeImage: "glitch_drink_large.jpg",
    ingredients: ["Энергетик", "Содовая", "Цветной сироп"],
    volume: "450 мл",
    price: 99,
  },
];